### ISSUE TITLE
One bad UFO kills the whole batch

### ISSUE THREAD

**Issue by cjdunn** [typemytype/batchRoboFontExtension#10]
Currently if Batch hits one non-generating UFO, ie non 1000UPM for OTF or quadratic curves when for OTF, the whole process stops. This is the traceback I get:
RuntimeError: maximum recursion depth exceeded

I would expect that Batch would skip a problematic UFO (and report it) rather than forcing the whole batch generate to stop. Thanks!

**Comment by typemytype** [comment]
this should be solved in the last updates

please test...

**Comment by typemytype** [comment]
Is this still an issue? Please close if not

Thanks

**Comment by cjdunn** [comment]
This appears to be resolved now, thank you!
