### ISSUE TITLE
HTML preview as option

### ISSUE THREAD

**Issue by nicksherman** [typemytype/batchRoboFontExtension#11]
It'd be nice if the HTML preview files were optional when generating.

**Comment by typemytype** [comment]
in the variable font part? 

(the web fonts part will always have html preview just to test the font quickly)

**Comment by nicksherman** [comment]
No, I just mean in general. Even when outputting normal OTFs, the web preview files are still generated. And even then, I don't necessarily always want those files even when I am making webfonts.

**Comment by typemytype** [comment]
In the Web Fonts pane Batch will always generate some test html, even if the web font is a normal otf or rtf...

The Batch Generate pane does not generate any html only a log file showing whats going on

**Comment by nicksherman** [comment]
Yeah, that test HTML is what I'm saying would be nice as an option instead of a requirement.

**Comment by typemytype** [comment]
see https://github.com/typemytype/batchRoboFontExtension/commit/305e7092591d8a20fac65adb9c6f2c28808ac772
