### ISSUE TITLE
folder support gone in new version

### ISSUE THREAD

**Issue by cjdunn** [typemytype/batchRoboFontExtension#15]
New version doesn't allow you to drop a folder onto the list to generate. This was a feature before that I REALLY liked using. Sometimes I need to generate many folders of UFOs at a time, so if I can drop 10 folder onto Batch it's much easier than opening one folder, drop UFOs, open next folder, drop UFOs … Please add this feature back! Thank you.

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/batchRoboFontExtension/commit/e342a7cfe2daddbe7aa6e323434dfa95c6c1979d
