### ISSUE TITLE
Unable to add files via the "Open" button

### ISSUE THREAD

**Issue by nicksherman** [typemytype/batchRoboFontExtension#18]
I noticed that when you hit the "Open" button at the top of the window, all the kinds of files one might want to add (UFOs, designSpace files) are unselectable. You can add them fine via drag-and-drop, but for some reason not via the button.

**Comment by typemytype** [comment]
solved in https://github.com/typemytype/batchRoboFontExtension/commit/f4d93e8be70a150657f984dd9dc62ef5d67eea8b

thanks
