### ISSUE TITLE
Option to generate variable fonts in TTF or CFF format

### ISSUE THREAD

**Issue by nicksherman** [typemytype/batchRoboFontExtension#19]

**Comment by frankrolf** [comment]
CFF2 files are generated in a 2-step process:
`buildmasterotfs -d foo.designspace` (builds dummy OTF files with overlap)
`buildcff2vf -d foo.designspace` (merges those OTFs)

`buildmasterotfs` needs to be run on UFOs without a processed layer.
See more info here: https://github.com/adobe-type-tools/afdko/issues/1154

**Comment by typemytype** [comment]
an option for CFF could be added since afdko is embedded

**Comment by typemytype** [comment]
see Batch 2.0
