### ISSUE TITLE
Generating CFF-flavored webfonts

### ISSUE THREAD

**Issue by nicksherman** [typemytype/batchRoboFontExtension#2]
Currently all fonts are converted to TTF when generating webfonts. This makes sense for some things like EOT, but it'd be nice to have the option of choosing TTF- or CFF-flavored fonts for each format.

**Comment by typemytype** [comment]
added an option to choose between otf - ttf flavored woofs.

https://github.com/typemytype/batchRoboFontExtension/commit/30b4e101ba5f478fdde520486027145bb68b2c52

thanks!
