### ISSUE TITLE
Variation Font axis tag

### ISSUE THREAD

**Issue by thomgb** [typemytype/batchRoboFontExtension#20]
The tag for an axis in the designspacedocument is not used in the generated font. Instead it will use the name of the axis and than the first four characters.

**Comment by typemytype** [comment]
varLib is not yet using that tag...
read https://github.com/fonttools/fonttools/issues/701

**Comment by LettError** [comment]
Can the axis map from the designspace be passed on to the varlib build? The support seems there in fonttools and the data is available in the designspace.

https://github.com/typemytype/batchRoboFontExtension/blob/master/Batch.roboFontExt/lib/variableFontGenerator/__init__.py#L511

**Comment by typemytype** [comment]
this should patch it db0a4f9f29294656a783a6be81dba1c469ec4f99
could someone this this before pushing the version number (a version number change, triggers Mechanic to send out notifications)

**Comment by LettError** [comment]
Seems to work on Version 1.8.3b (built 1702022141)
Does not appear in Version 2.0b (built 1707261639)

Erik
