### ISSUE TITLE
Web Fonts: generates OTF without the box being checked

### ISSUE THREAD

**Issue by LaPolice** [typemytype/batchRoboFontExtension#3]
If I generate WOFF + WOFF2 files without checking the boxe "Save OTF" I end up with OTF files anyway (with the _web Suffix).
I'm using the current version of Batch along with the latest RF beta (1.7b (built 1601082309)) with 10.9.5.

**Comment by typemytype** [comment]
fixed here https://github.com/typemytype/batchRoboFontExtension/commit/7351f320f787ebed395deb3a740c4df769dab27d
