### ISSUE TITLE
Custom axis names cause problems with generation

### ISSUE THREAD

**Issue by nicksherman** [typemytype/batchRoboFontExtension#31]
This may be related to #20(?) but unregistered axis names seem to break the generation process for variable fonts. Even changing the capitalization of the axis name from "weight" to "Weight" results in the final fonts not being successfully generated. You can see the "tmp_" fonts quickly popping in and out of the directory, and the report in "Batch Generated Variable Fonts Report.txt" seems OK, but I don't think the final fonts are saved successfully unless you stick to registered axis names.

**Comment by typemytype** [comment]
The tag of unregistered axis must be capitalised and 4 char long. The axis name is not really important.

Batch has a debug pref where you can keep and inspect the temp fonts:

```
from mojo.UI import setDefault
setDefault("Batch.Debug", True)
```

**Comment by nicksherman** [comment]
I have tried both upper and lowercase tags with no luck. Also, after further investigation, it seems even some of the registered axes also don’t work (ital and opsz). I’ll put together some simple example files and share with the report file etc shortly.

**Comment by nicksherman** [comment]
OK, it only seems to be an issue when running Batch with RoboFont 1.8 / UFO2. It's still a curious thing, but understandably not a high priority issue. Perhaps it could be nice to at least get a warning message when running from older versions?

**Comment by typemytype** [comment]
oh, this fails in RF1.8 with the current Batch?

its possible you have to downgrade Batch...

Im considering not support RF 1.8 anymore with Batch in the near future

**Comment by nicksherman** [comment]
Yeah, this is running the latest Batch from RoboFont 1.8. It is weird because using weight/wght, width/wdth, and slant/slnt for axis names and tags works fine. I’ll try downgrading to an older version to see if that changes anything.

**Comment by typemytype** [comment]
or you could install the latest fontTools in the folder `sys_path_override` in `<user>/Application Support/RoboFont/sys_path_override` a special folder where RF1.8 looks and overwrites internal embedded packages. For RF3 the folder is called `external_packages`.

**Comment by typemytype** [comment]
and ... RF1.8 is gone ... heavily advised to use RF3 :)

**Comment by nicksherman** [comment]
I know, I know :) … But I was teaching a workshop last weekend for Type@Cooper West where all the students are still using 1.8.
