### ISSUE TITLE
naming consistency of generated fonts

### ISSUE THREAD

**Issue by LaPolice** [typemytype/batchRoboFontExtension#4]
With a font file named: BIG-Bang-Regular-A001.ufo

When generating Web Fonts, you get:
– BIG-Bang-Regular-A001_web.woff

When generating "Desktop" Fonts, you get:
– BIGBang-Regular.woff

I'd suggest to keep the original filename (for designers using it for versioning) and syntax.

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/batchRoboFontExtension/commit/52289c015953c92c9bd3ab7839ff620060924dc9
