### ISSUE TITLE
[ds5] Strange things happen when Sources are empty and you hit Generate

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/batchRoboFontExtension#68]
If the sources table is empty, and all checkboxes are checked, `Generate` will:
- Delete the output folder
- Hang on this state:
<img width="418" alt="image" src="https://github.com/typemytype/batchRoboFontExtension/assets/12752088/24071698-48cb-46e2-aaf4-52f70c1831f1">

```
Traceback (most recent call last):
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/vanilla/dialogs.py", line 134, in completionHandler_
  File "/Applications/RoboFont-4_4b2.app/Contents/Resources/lib/python3.9/ezui/controllers.py", line 475, in _internalGetFolderCallbackReroute
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batch.py", line 241, in result
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Batch.roboFontExt/lib/batchGenerators/batchTools.py", line 100, in save
FileNotFoundError: [Errno 2] No such file or directory: '[redacted]/Batch Generate Report.txt'
```

Maybe it should just be a pop-up that says "Please add source(s) before attempting to generate"

**Comment by typemytype** [comment]
mmm, not nice

**Comment by ryanbugden** [comment]
The folder seems to be deleted and then remade in normal uses as well.

**Comment by ryanbugden** [comment]
Big problem if you choose to generate into the same folder as the source(s)! Or any folder that's not empty for that matter...

**Comment by typemytype** [comment]
the destination folder is cleared... 

an option is a yes/no message: The destination folder is not empty. Do you want to continue?

**Comment by ryanbugden** [comment]
Could it just drop files in there? Does it need to delete and reconstruct the folder?

**Comment by LettError** [comment]
Sources should never be overwritten. Is that what we're discussing?

**Comment by typemytype** [comment]
before [this commit](https://github.com/typemytype/batchRoboFontExtension/commit/46edb9ca4e068426e71635dddd544329b4c09e98) batch was clearing the destination folder completely... this is a bit dramatic, now only the sub format folders "Desktop", "Web", "Variable" are cleared
