### ISSUE TITLE
[ds5] Woffs are generated instead of woff2s

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/batchRoboFontExtension#69]
For Web and Variable folders

**Comment by ryanbugden** [comment]
Also, cosmetic feedback. Could we change `Woff 2` in the UI to `WOFF2` to keep with the all-caps and the [spec](https://www.w3.org/TR/2022/REC-WOFF2-20220310/#woff20Header)? I'd do it myself, but I don't want to break any label parsing that might be in there.

**Comment by typemytype** [comment]
Mmm they should be woff2 see https://github.com/typemytype/batchRoboFontExtension/blob/a1720ac5c6a325d68e9ba84db660f7902d4f82e2/Batch.roboFontExt/lib/batchGenerators/batchTools.py#L284

Will check on the cosmetic change 💄

**Comment by ryanbugden** [comment]
Should the file ending (and output folder) be "woff2" as well? 

https://github.com/typemytype/batchRoboFontExtension/blob/a1720ac5c6a325d68e9ba84db660f7902d4f82e2/Batch.roboFontExt/lib/batchGenerators/batchTools.py#L282

**Comment by ryanbugden** [comment]
Looks like it's working!
