### ISSUE TITLE
[ds5] Keep file names isn't honoring .designspace `filename` tag

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/batchRoboFontExtension#72]
<img width="529" alt="image" src="https://github.com/typemytype/batchRoboFontExtension/assets/12752088/1dbd9d63-a9fa-4595-b951-6248675b065e">
<img width="964" alt="image" src="https://github.com/typemytype/batchRoboFontExtension/assets/12752088/ee3d28ca-d1f8-4fb5-8f5e-a58cbf915d2c">

<img width="282" alt="image" src="https://github.com/typemytype/batchRoboFontExtension/assets/12752088/69ee3487-7a86-4077-a8cd-7640d39e7ca8">

**Comment by typemytype** [comment]
silly the radio button has value `0`  when **Keep file names** is selected...

**Comment by ryanbugden** [comment]
Looks like this is working!
