### ISSUE TITLE
[ds5] Add woff2 to `supportedFileTypes`?

### ISSUE THREAD

**Issue by ryanbugden** [typemytype/batchRoboFontExtension#75]
https://github.com/typemytype/batchRoboFontExtension/blob/b687dbfcfe92c6df830322c0c1a15d3167d15237/Batch.roboFontExt/lib/batch.py#L81

**Comment by typemytype** [comment]
yep, woff is actually always woff2 :)

**Comment by ryanbugden** [comment]
Complete as of https://github.com/typemytype/batchRoboFontExtension/pull/80
Batch recognizes woff2 as a source for generation, but roundtrip through font object seems to still be unsuccessful without addressing https://github.com/simoncozens/fontFeatures/issues/62
