### ISSUE TITLE
Temporary FDK / TTF files do not get deleted

### ISSUE THREAD

**Issue by jeremymickel** [typemytype/batchRoboFontExtension#79]
Would be nice for the temporary files to get removed once the variable font generates.

**Comment by typemytype** [comment]
Did you check the **Batch Settings** for `Debug`? 

If this is on Batch will keep all the temp file

<img width="439" alt="image" src="https://github.com/typemytype/batchRoboFontExtension/assets/1190358/3de98e09-7ca7-4815-a91b-12d69ebc4837">

**Comment by jeremymickel** [comment]
Ah perfect, thank you!
