### ISSUE TITLE
Removed Overlap button not working

### ISSUE THREAD

**Issue by cjdunn** [typemytype/batchRoboFontExtension#8]
I just noticed that files generated from Batch don't get overlap removed when only the "Remove Overlap" button is checked. The only way I can get it to remove overlap is with both "Remove Overlap" AND "Decompose" buttons checked. I think this was working correctly before, so I'm not sure at what point something might have changed.

I've been able to reproduce with multiple different UFOs using the latest Beta version of RF [1605141504] and also with the previous public release [1.6]. Also doesn't seem to matter if the "Remove Overlap" preference is set to in the font info or not, and it's the same for both OTF and TTF. 

This isn't a problem for the "Web Fonts" OTF or TTF option in Batch – overlaps get removed correctly for both of these options. If I use File > Generate and check the "Remove Overlap" button then everything works, and same if I use a script to generate. The problem only happens in Batch. Thanks!

**Comment by typemytype** [comment]
could you test https://github.com/typemytype/batchRoboFontExtension/commit/36d2d827b3cd99a712e7de1129a68be427ae9fe6

you will need to download it directly form github, I didnt touched the version number and will not yet endup in a Mechanic update notification.

thanks

**Comment by cjdunn** [comment]
Awesome, this works great. I tested on OTF and TTF and using different combinations of the buttons. All seems to be working as expected now, thanks!
